config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "registrations" }, class_name: "FormUser"
  get "users/:id" => "users#profile"

  # Bookings
  resources :bookings
  get "bookings/:id/cancel_by_nomad" => "bookings#cancel_by_nomad"    

  get "bookings/:id/payment" => "bookings#payment"
  get "bookings/:id/pay" => "bookings#pay"

  get "bookings/:id/payment_cancelled" => "bookings#payment_cancelled"
  get "bookings/:id/payment_received" =>  "bookings#payment_received"

  get  "stay/:stay_id/room/:room_id/book" => "bookings#new"
  post "stay/:stay_id/room/:room_id/book" => "bookings#create"

  # Stays, rooms, bookings
  resources :stays do
    resources :rooms
  end  

  # Stay photos
  resources :stay_photos 
  get "stay_photos/:id/set_as_cover" => "stay_photos#set_as_cover"

  # Admin
  namespace :admin do
    resources :stays
    resources :bookings

    get "bookings/:id/accept" => "bookings#accept"
    get "bookings/:id/reject" => "bookings#reject"
    get "bookings/:id/cancel_by_host" => "bookings#cancel_by_host"
  end


  # Dashboard
  # Shows next bookings (nomad)
  # Shows pending booking requests (host)
  # Shows big picture of community interaction later
  # get "dashboard"


  # New booking 
  # /bookings/new

  # Dashboard
  # 
  # See current bookings as a host
  # /host/dashboard
  # See current bookings as a nomad
  # /nomad/dashboard

  # Show
  # 
  # See a booking as a nomad
  # /nomad/booking/id
  # See and manage a booking as a host 
  # /host/booking/id



  # Example of regular route:
  #   get "products/:id" => "catalog#view"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get "products/:id/purchase" => "catalog#purchase", as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get "short"
  #       post "toggle"
  #     end
  #
  #     collection do
  #       get "sold"
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get "recent", on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post "toggle"
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/stay.rb
class Stay < ActiveRecord::Base
  belongs_to :user

  has_one  :apartment,    :dependent => :destroy
  has_one  :house,        :dependent => :destroy

  # has_many :rooms #, through: :apartment
  # has_many :rooms #, through: :house
  has_many :rooms,                dependent: :delete_all
  has_many :bookings,             dependent: :delete_all
  has_many :stay_photos,          dependent: :delete_all

  accepts_nested_attributes_for :stay_photos
  accepts_nested_attributes_for :apartment
  accepts_nested_attributes_for :house

  geocoded_by :full_address          # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  validates_presence_of       :title
  validates_presence_of       :description

  validates :accomodation_type, presence: true, allow_blank: false

  validates_presence_of       :street_address
  validates_presence_of       :country_code
  validates_presence_of       :country_name
  validates_presence_of       :city
  validates_presence_of       :full_address

  validates_presence_of       :latitude
  validates_presence_of       :longitude


  validates_inclusion_of :wifi,                             in: [true, false]
  validates_inclusion_of :mobile_data,                      in: [true, false]

  validates_inclusion_of :terrace,                          in: [true, false]
  validates_inclusion_of :router_access,                    in: [true, false]
  validates_inclusion_of :desk,                             in: [true, false]

  validates_inclusion_of :service_pickup,                   in: [true, false]
  validates_inclusion_of :service_laundry,                  in: [true, false]
  validates_inclusion_of :service_cleaning,                 in: [true, false]
  validates_inclusion_of :service_sim_card,                 in: [true, false]

  validates :service_pickup_price,    allow_blank: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :service_laundry_price,   allow_blank: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :service_cleaning_price,  allow_blank: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :service_sim_card_price,  allow_blank: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # validates_inclusion_of :available,                        in: [true, false]

  validates :monthly_price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def attached_rooms
    container = apartment || house
    container.rooms
  end

  def build_full_address
    if state
      full_address = street_address + ", " + city + ", " + state + ", " + country_name
    else
      full_address = street_address + ", " + city + ", " + country_name
    end
  end

  # Get all the bookings for this stay, so we can
  # render the availability calendar
  def booked_dates
    dates = []

    bookings.each { |booking|
      from = booking.date_from.strftime("%d/%m/%Y") 
      to   = booking.date_to.strftime("%d/%m/%Y")

      dates << [from, to]
    }

    dates
  end

  def offers_extra_services?
    service_pickup || service_cleaning || service_laundry || service_sim_card
  end

  def pending_bookings
    bookings.where( status: 'pending' )
  end

  def pending_payment_bookings
    bookings.where( status: 'accepted', paid: 'false' )
  end

  def ready_bookings
    bookings.where( status: 'ready', paid: 'true' )
  end

  def cover_photo
    stay_photos.where( cover: true ).first
  end

  # def get_country_name
  #   debugger

  #   country = ISO3166::Country[country]
  #   # country.translations[I18n.locale.to_s] || country.name
  #   country.name
  # end  

end

app/controllers/admin/stays_controller.rb
class Admin::StaysController < ApplicationController

  public

    def show
      @stay = Stay.find params[:id]

      @booked_dates = @stay.booked_dates
    end

    def index
      
    end

end

app/controllers/stays_controller.rb
class StaysController < ApplicationController

  public

    def index
      if params[:q]
        query = params[:q].reject {|i,j|  i == "house_nomad_house_eq_any" && j == "0"}
        @q = Stay.ransack(query)
        @stays = @q.result(distinct: true)      
      else
        @q = Stay.ransack(params[:q])
        @stays = @q.result(distinct: true)
      end
    end      

    def show
      @stay = Stay.find params[:id]
      @stay_photos = @stay.stay_photos.all

      @booked_dates = @stay.booked_dates
    end

  	def new
  		@stay = Stay.new
      @stay_photos = @stay.stay_photos.build    

      @stay.apartment = Apartment.new
      @stay.house =     House.new
  	end

  	def create
  		input = params[:stay]

      if input[:accomodation_type] == "Select one"
        accomodation_type = ""
      else
        accomodation_type = input[:accomodation_type]
      end

      @stay = Stay.new(stay_params)
      @stay.accomodation_type = accomodation_type
      @stay.user_id = current_user.id
      @stay.country_name = ISO3166::Country[@stay.country_code]
      @stay.full_address = @stay.build_full_address

      # Apartment / House

      if input[:accomodation_type] == "House"

        house_params = input[:house_attributes]

        @stay.house = House.new(
          :stay_id => @stay.id,

          :garden  => house_params[:garden],
          :terrace  => house_params[:terrace],
          :alarm  => house_params[:alarm],          
          :nomad_house  => house_params[:nomad_house]
        )

      elsif input[:accomodation_type] == "Apartment"

        apartment_params = input[:apartment_attributes]

        @stay.apartment = Apartment.new(
          :stay_id => @stay.id,

          :nrooms       => apartment_params[:nrooms],
          :floor        => apartment_params[:floor],
          :lift         => apartment_params[:lift],          
          :security     => apartment_params[:security]
        )

      end    

      @stay.save!  

      if @stay.persisted?
        params[:stay_photos][:file].each do |a|
          @stay_photo = @stay.stay_photos.create!(:file => a, :stay_id => @stay.id)
        end  

        # First photo will be the cover one automatically
        @stay.stay_photos.first.update(cover: true)

        redirect_to :action => 'show', :id => @stay.id
      else
        # Renders the nested form for the child that was not created before
        @stay.apartment = Apartment.new     if input[:accomodation_type] == "House"
        @stay.house = House.new             if input[:accomodation_type] == "Apartment"

        render "new"
      end    

  	end

    def edit
      @stay = Stay.find params[:id]
    end

    def update
      @stay = Stay.find(params[:id])

      @stay.country_name = ISO3166::Country[country_code]
      @stay.full_address = @stay.build_full_address

      if @stay.update(stay_params)

        if params[:stay_photos]
          params[:stay_photos][:file].each do |a|
            @stay_photo = @stay.stay_photos.create!(:file => a, :stay_id => @stay.id)
          end  
        end

        redirect_to @stay
      else
        render "edit"
      end         
    end

    def destroy
      @stay = Stay.find(params[:id])
      @stay.destroy
      redirect_to stays_path
    end

  private

    def stay_params
      params.require(:stay).permit(:title, :description, :accomodation_type,
                                   :latitude, :longitude, :street_address, :city, :state, :country_code,
                                   :wifi, :wifi_speed, :mobile_data, :mobile_data_speed,
                                   :terrace, :router_access, :desk,
                                   :service_pickup, :service_laundry, :service_cleaning, :service_sim_card,
                                   :service_pickup_price, :service_laundry_price, :service_cleaning_price, :service_sim_card_price,
                                   :monthly_price,
                                   :available,
                                   stay_photos_attributes: [:id, :stay_id, :file]
                                   )
    end

end

app/helpers/stays_helper.rb
module StaysHelper
end

app/views/stays/_form_apartment.haml
/%p Great ! Can you give us some details about this apartment ?

= a.input :nrooms,        :label => "How many rooms does it have ?", collection: 1..15
= a.input :floor,         :label => "In what floor is it ?"
= a.input :lift,          :label => "Does the building have a lift ?"
= a.input :security,      :label => "Is there some sort security in the building ?"

/ Later we can showa message depending on which floor is this apartment
/ "Wow, 4 floors is high enough ! Does the building have a lift ?"

app/views/stays/_form_house.haml
/%p Great ! Can you give us some details about this house ?

= h.input :garden,        	:label => "Does it have a garden or green area ?"
= h.hint "Nomads who are working hard also appreciate to take some fresh air !"

= h.input :terrace,         :label => "Does it have a terrace?"

= h.input :alarm,          	:label => "Is there an alarm ?"
= h.hint "Security is also important in order to feel comfortable in a new place."

= h.input :nomad_house,     :label => "Will this be a nomad house ?"
= h.hint "Nomad houses are just starting to pop out all over the world, gathering like-minded people in one house."

app/views/stays/_form_room.haml
.alert.alert-warning
  In order to add a room, please add first the apartment or house it belongs to. You will then be able to add as many rooms you want to your place !

app/views/stays/_map.haml
/ #map-container{:style => "width: 800px;"}
/  #map{:style => "width: 800px; height: 400px;"}

#map-container
  #map

app/views/stays/_new_stay_map.haml
.map-container{:style => "width: auto;"}
  #map{:style => "width: auto; height: 230px;"}

app/views/stays/_stay_card.haml
.stay-card
  .photo{:style => "background-image: url(#{image_path stay.cover_photo.file.card.url})"}
    .price
      = stay.monthly_price
      = "$ / month"            
  .info
    .title
      = stay.title

app/views/stays/edit.haml
#stays-edit.has-padding

  - content_for :title do
    Update your stay

  - content_for :subheader do

    - if current_user.stays.any?
      = link_to admin_stays_path do
        Host dashboard
    - else
      = link_to root_path do
        Home

    = link_to 'Remove this stay', stay_path(@stay.id), method: :delete 

  = simple_form_for @stay, :method => :put, :html => { :multipart => true } do |f|      
    = f.input :latitude, :as => :hidden
    = f.input :longitude, :as => :hidden

    / Accomodation

    = f.input  :accomodation_type, 
               :as => :hidden      

    / Description

    %h3 Write a beautiful description

    .panel.panel-default
      .panel-body
        .input-group
          = f.input :title
          = f.hint "Type something that will attract nomads. For example: Fully furnished apartment by the sea"
          = f.input :description


    / Accomodation type

    - if @stay.accomodation_type == "Apartment"

      / Apartment 

      #accomodation_is_apartment

        %h3 About your apartment

        .panel.panel-default
          .panel-body
            .input-group      
              = f.simple_fields_for :apartment do |a|
                = render :partial => 'form_apartment', :locals => {:a => a}

    - elsif @stay.accomodation_type == "House"

      / House          

      #accomodation_is_house

        %h3 About your house

        .panel.panel-default
          .panel-body
            .input-group          
              = f.simple_fields_for :house do |h|
                = render :partial => 'form_house', :locals => {:h => h}

    / Location

    %h3 Where is it ?
    %p Don't worry, we will only offer an approximate location   until booking is completed

    .panel.panel-default
      .panel-body

        .row
          .col-md-6

            .input-group
              = f.input :country_code
              = f.input :state 
              = f.input :city
              = f.input :street_address
              = f.hint "Once you have filled those fields please fine-grain the position by clicking on the map"

          .col-md-6

            = render "new_stay_map"                

    / Connection

    %h3 What sort of connetion is available ?
    %p Remember, only stays that have an internet connection will be listed

    .panel.panel-default
      .panel-body
        .input-group
          = f.input :wifi
          = f.input :wifi_speed,
            :label => "What is the speed of your internet connection ?",
            collection: internet_speed_types,
            include_blank: false              
          = f.input :router_access, :label => "Does your guest has physical access to the router ? (in case he needs to restart it)"
          = f.input :mobile_data
          = f.input :mobile_data_speed,
            :label => "What is the speed of your mobile data connection in your place ?",
            collection: internet_speed_types,
            include_blank: false                   

    / Amenities

    %h3 Does your place offer amenities ?

    .panel.panel-default
      .panel-body
        .input-group
          = f.input :terrace
          = f.input :desk
          = f.hint "Having a desk will give you a better score"

    / Price

    %h3 What will be the monthly cost ?

    .panel.panel-default
      .panel-body
        .input-group      
          = f.input :monthly_price, wrapper: :vertical_input_group, hint: "Remember, the minimum stay length will be 1 month" do
            %span.input-group-addon US $
            = f.input_field :monthly_price, class: "form-control"

    / Extra services

    %h3 Would you like to offer any extra service ?
    %p Make some extra bucks by offering a more comfortable stay, or give it for free !

    .panel.panel-default
      .panel-body#extra-services
        / TODO: Limit HTML5 numeric inputs to >= 0 and < 200
        = f.input :service_laundry,   :label => "Take care of your nomad's laundry"

        = f.input :service_laundry_price, wrapper: :vertical_input_group, label: false do
          %span.input-group-addon US $
          = f.input_field :service_laundry_price, class: "form-control"

        = f.input :service_cleaning, :label => "Weekly cleaning of the stay"

        = f.input :service_cleaning_price, wrapper: :vertical_input_group, label: false do
          %span.input-group-addon US $
          = f.input_field :service_cleaning_price, class: "form-control"

        = f.input :service_sim_card,  :label => "Local SIM Card"

        = f.input :service_sim_card_price, wrapper: :vertical_input_group, label: false do
          %span.input-group-addon US $
          = f.input_field :service_sim_card_price, class: "form-control"    

        = f.input :service_pickup,    :label => "Airport Pickup"

        = f.input :service_pickup_price, wrapper: :vertical_input_group, label: false do
          %span.input-group-addon US $
          = f.input_field :service_pickup_price, class: "form-control"        

    / Status

    %h3 Status

    .panel.panel-default
      .panel-body
        .input-group    
          = f.input :available,   :label => "Is your stay currently active ?"
          = f.hint "If not, your stay won't be visible on the website"

    / Photos

    %h3 Photos
    %p.subtitle Photos are extremely important, put as many as possible.
    %p.subtitle 
      %u A lack of photos or poor quality of them will result in your new addition being cancelled.

    .panel.panel-default
      .panel-body
        .input-group   
          .photos
            - @stay.stay_photos.each do |photo|
              .photo
                = image_tag photo.file.thumb
                .delete
                  = link_to "Delete", photo, method: :delete 
                .set-as-cover
                  - unless photo.cover
                    = link_to "Set as cover", "/stay_photos/#{photo.id}/set_as_cover"

          / = f.fields_for :stay_photos do |p|
          / .field
          / = p.label :file
          / %br
          = f.file_field :file, :multiple => true, name: "stay_photos[file][]"                  

    .submit
      = f.button :submit, "Update"

app/views/stays/index.haml
#stays-index

  - content_for :title do
    Find your next stay

  .form-container

    = search_form_for @q, :url => stays_path do |f|

      .panel.panel-default
        .panel-body
          .form-group
            = f.input_field :full_address_cont,
                      label: false,
                      class: "form-control input-lg"

            .form-bottom-wrapper

              .form-bottom

                .accomodation-type 
                  = f.input_field :accomodation_type_eq, 
                            collection: accomodation_types,
                            include_blank: false,
                            label: false, class: "form-control input-lg"


                .price-range 
                  = f.input :monthly_price_gt, wrapper: :vertical_input_group, label: false do
                    %span.input-group-addon US $
                    = f.input_field :monthly_price_gt, class: "form-control input-lg"

                  = f.input :monthly_price_lt, wrapper: :vertical_input_group, label: false do
                    %span.input-group-addon US $
                    = f.input_field :monthly_price_lt, class: "form-control input-lg"

                = f.submit "Search", class: "form-control input-lg"


            / = f.input :wifi_speed_gt, 
            /           collection: internet_speed_types,
            /           include_blank: false,
            /           label: "Wifi speed greater than"           

            / = f.input :house_nomad_house_eq_any, 
            /           label: "Only show nomad houses",
            /           as: :boolean

            / = f.input_field :updated_at_gt,
            /           :data => {:provide => "datepicker"},
            /           label: "Available from"

            / = f.input_field :updated_at_lt,
            /           :data => {:provide => "datepicker"},
            /           label: "Available to"
      

  .stay-cards-container

    - if @stays.any?
      - @stays.each do |stay|
        = link_to stay_path(stay.id) do
          = render :partial => 'stay_card', :locals => {:stay => stay}

    - if @stays.empty?
      %h3 We didn't find anything that strictly matches your criteria, but...

  / Important: We will never show an empty result ! If nothing comes up, we suggest something anyway    

  / See Top Picks
  / See Latest
  / See Hottest

  / Filter by region

  / Filter by availability (booking period) -> If filter not active, show them all

  / Filter by weather (WARM or COLD) OR by terrain (SEA-SIDE, MOUNTAINS, FIELDS)

  / Filter by extra services provided

  / Launch as beta first
  / Provide invitations to hosts
  / Start only in one region, then expand availability to other places (allows to keep promoting for longer)

app/views/stays/new.haml
#stays-new.has-padding

  - content_for :title do
    Add a new stay

  - content_for :subheader do
    - if current_user.stays.any?
      = link_to admin_stays_path do
        Host dashboard
    - else
      = link_to root_path do
        Home

  = simple_form_for @stay, :method => :post, :html => { :multipart => true } do |f|    
    = f.input :latitude, :as => :hidden
    = f.input :longitude, :as => :hidden

    / Accomodation Type

    %h3 What sort of accomodation do you offer ?

    = f.input :accomodation_type, 
              collection: accomodation_types,
              include_blank: false,
              label: "Accomodation"

    / Room

    #accomodation_is_room
      = render :partial => 'form_room'

    #form-details

      / Description

      %h3 Write a beautiful description

      .panel.panel-default
        .panel-body
          = f.input :title
          = f.hint "Type something that will attract nomads. For example: Fully furnished apartment by the sea"
          = f.input :description

      / Apartment 

      #accomodation_is_apartment

        %h3 About your apartment

        .panel.panel-default
          .panel-body
            = f.simple_fields_for :apartment do |a|
              = render :partial => 'form_apartment', :locals => {:a => a}

      / House          

      #accomodation_is_house

        %h3 About your house

        .panel.panel-default
          .panel-body
            = f.simple_fields_for :house do |h|
              = render :partial => 'form_house', :locals => {:h => h}

      / Location

      %h3 Where is it ?
      %p.subtitle Don't worry, we will only offer an approximate location   until booking is completed

      .panel.panel-default
        .panel-body

          .row
            .col-md-6

              = f.input :country_code
              = f.input :state 
              = f.input :city
              = f.input :street_address
              = f.hint "Once you have filled those fields please fine-grain the position by clicking on the map"

            .col-md-6

              = render "new_stay_map"                

      / Connection

      %h3 What sort of connetion is available ?
      %p.subtitle Remember, only stays that have an internet connection will be listed

      .panel.panel-default
        .panel-body
          = f.input :wifi
          = f.input :wifi_speed,
            :label => "What is the speed of your internet connection ?",
            collection: internet_speed_types,
            include_blank: false              
          = f.input :router_access, :label => "Does your guest has physical access to the router ? (in case he needs to restart it)"
          = f.input :mobile_data
          = f.input :mobile_data_speed,
            :label => "What is the speed of your mobile data connection in your place ?",
            collection: internet_speed_types,
            include_blank: false                   

      / Amenities

      %h3 Does your place offer amenities ?

      .panel.panel-default
        .panel-body
          = f.input :terrace
          = f.input :desk
          = f.hint "Having a desk will give you a better score"

      / Price

      %h3 What will be the monthly cost ?

      .panel.panel-default
        .panel-body
          = f.input :monthly_price, wrapper: :vertical_input_group, hint: "Remember, the minimum stay length will be 1 month" do
            %span.input-group-addon US $
            = f.input_field :monthly_price, class: "form-control"

      / Extra services

      %h3 Would you like to offer any extra service ?
      %p.subtitle Make some extra bucks by offering a more comfortable stay, or give it for free !

      .panel.panel-default
        .panel-body#extra-services
          / TODO: Limit HTML5 numeric inputs to >= 0 and < 200
          = f.input :service_laundry,   :label => "Take care of your nomad's laundry"

          = f.input :service_laundry_price, wrapper: :vertical_input_group, label: false do
            %span.input-group-addon US $
            = f.input_field :service_laundry_price, class: "form-control"

          = f.input :service_cleaning, :label => "Weekly cleaning of the stay"

          = f.input :service_cleaning_price, wrapper: :vertical_input_group, label: false do
            %span.input-group-addon US $
            = f.input_field :service_cleaning_price, class: "form-control"

          = f.input :service_sim_card,  :label => "Local SIM Card"

          = f.input :service_sim_card_price, wrapper: :vertical_input_group, label: false do
            %span.input-group-addon US $
            = f.input_field :service_sim_card_price, class: "form-control"    

          = f.input :service_pickup,    :label => "Airport Pickup"

          = f.input :service_pickup_price, wrapper: :vertical_input_group, label: false do
            %span.input-group-addon US $
            = f.input_field :service_pickup_price, class: "form-control"          

      / Photos

      %h3 Photos
      %p.subtitle Photos are extremely important, put as many as possible.
      %p.subtitle 
        %u A lack of photos or poor quality of them will result in your new addition being cancelled.

      .panel.panel-default
        .panel-body
          = f.fields_for :stay_photos do |p|
            .field
              = p.label :file
              %br
                = p.file_field :file, :multiple => true, name: "stay_photos[file][]"

      = f.button :submit, "Add"

app/views/stays/show.haml
- content_for :title do
  / #{@stay.title}
  Nomad Stays

/- content_for :subheader do
/  %p= link_to "Book this stay", new_booking_path(stay_id: @stay.id)

#stays-show

  .photo-overlay
    .title
      #{@stay.title}
    .price
      #{@stay.monthly_price} $ / month
    .photo{:style => "background-image: url(#{image_path @stay.cover_photo.file_url})"}

  .photo-subheader
    .extra-services
      .service
        .title
          Laundry
        .price
          25 $ monthly 
      .service
        .title
          Cleaning
        .price
          15 $ monthly    
      .bookit   
        = link_to "Book", new_booking_path(stay_id: @stay.id)

  .content

    .overview
      .description
        = @stay.description
        
        .rate
          %h3 Rate by other nomads
          %h4 Proximity

          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
           
          %h4 Connectivity
          
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star-empty{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star-empty{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star-empty{"aria-hidden" => "true"}

          %h4 Luminosity
          
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          %span.glyphicon.glyphicon-star-empty{"aria-hidden" => "true"}                     
          
      .photos
        - @stay_photos.each do |p|
          = image_tag p.file.thumb

  .map-wrapper
    #latitude= @stay.latitude
    #longitude= @stay.longitude
    = render "map"