config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "registrations" }, class_name: "FormUser"
  get "users/:id" => "users#profile"

  # Bookings
  resources :bookings
  get "bookings/:id/cancel_by_nomad" => "bookings#cancel_by_nomad"    

  get "bookings/:id/payment" => "bookings#payment"
  get "bookings/:id/pay" => "bookings#pay"

  get "bookings/:id/payment_cancelled" => "bookings#payment_cancelled"
  get "bookings/:id/payment_received" =>  "bookings#payment_received"

  get  "stay/:stay_id/room/:room_id/book" => "bookings#new"
  post "stay/:stay_id/room/:room_id/book" => "bookings#create"

  # Stays, rooms, bookings
  resources :stays do
    resources :rooms
  end  

  # Stay photos
  resources :stay_photos 
  get "stay_photos/:id/set_as_cover" => "stay_photos#set_as_cover"

  # Admin
  namespace :admin do
    resources :stays
    resources :bookings

    get "bookings/:id/accept" => "bookings#accept"
    get "bookings/:id/reject" => "bookings#reject"
    get "bookings/:id/cancel_by_host" => "bookings#cancel_by_host"
  end


  # Dashboard
  # Shows next bookings (nomad)
  # Shows pending booking requests (host)
  # Shows big picture of community interaction later
  # get "dashboard"


  # New booking 
  # /bookings/new

  # Dashboard
  # 
  # See current bookings as a host
  # /host/dashboard
  # See current bookings as a nomad
  # /nomad/dashboard

  # Show
  # 
  # See a booking as a nomad
  # /nomad/booking/id
  # See and manage a booking as a host 
  # /host/booking/id



  # Example of regular route:
  #   get "products/:id" => "catalog#view"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get "products/:id/purchase" => "catalog#purchase", as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get "short"
  #       post "toggle"
  #     end
  #
  #     collection do
  #       get "sold"
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get "recent", on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post "toggle"
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable, #, :validatable
         :omniauthable, omniauth_providers: [:twitter, :google_oauth2]

  has_many :identities,           dependent: :delete_all
  has_many :stays,                dependent: :delete_all
  has_many :bookings,             dependent: :delete_all

  def twitter
    identities.where( provider: 'twitter' ).first
  end

  def google_oauth2
    identities.where( provider: 'google_oauth2' ).first
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_all_data
    email? &&
    first_name? &&
    last_name? &&
    birthdate? &&
    origin_country?
  end

end	                

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# before_action :authenticate_user!

	def profile
		user_signed_in?

	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/host_dashboard.haml
.host-dashboard

  - content_for :title do
    Host dashboard

  - content_for :subheader do
    = link_to new_stay_path do
      Rent out a new stay

  - current_user.stays.each do |stay|
    = link_to stay_path(stay.id) do
      .stay-card= stay.title

  %h3 Pending for approval

  - current_user.stays.each do |stay|
    - stay.pending_bookings.each do |booking|
      .booking
        = link_to stay_booking_path(stay_id: stay.id, id: booking.id) do
          #{image_tag(booking.user.photo, class: "gravatar")}
          #{booking.user.first_name} would like to stay in #{booking.stay.title} from #{booking.date_from} to #{booking.date_to} 

  %h3 Waiting for payment

  - current_user.stays.each do |stay|
    - stay.pending_payment_bookings.each do |booking|
      .booking
        = link_to stay_booking_path(stay_id: stay.id, id: booking.id) do
          #{image_tag(booking.user.photo, class: "gravatar")}
          #{booking.user.first_name} would like to stay in #{booking.stay.title} from #{booking.date_from} to #{booking.date_to}              

  %h3 Next arrivals

  - current_user.stays.each do |stay|
    - stay.ready_bookings.each do |booking|
      .booking
        = link_to stay_booking_path(stay_id: stay.id, id: booking.id) do
          #{image_tag(booking.user.photo, class: "gravatar")}
          #{booking.user.first_name} would like to stay in #{booking.stay.title} from #{booking.date_from} to #{booking.date_to}        

app/views/users/profile.haml
= image_tag current_user.photo, :class => "gravatar"
#{current_user.full_name}