config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "registrations" }, class_name: "FormUser"
  get "users/:id" => "users#profile"

  # Bookings
  resources :bookings
  get "bookings/:id/cancel_by_nomad" => "bookings#cancel_by_nomad"    

  get "bookings/:id/payment" => "bookings#payment"
  get "bookings/:id/pay" => "bookings#pay"

  get "bookings/:id/payment_cancelled" => "bookings#payment_cancelled"
  get "bookings/:id/payment_received" =>  "bookings#payment_received"

  get  "stay/:stay_id/room/:room_id/book" => "bookings#new"
  post "stay/:stay_id/room/:room_id/book" => "bookings#create"

  # Stays, rooms, bookings
  resources :stays do
    resources :rooms
  end  

  # Stay photos
  resources :stay_photos 
  get "stay_photos/:id/set_as_cover" => "stay_photos#set_as_cover"

  # Admin
  namespace :admin do
    resources :stays
    resources :bookings

    get "bookings/:id/accept" => "bookings#accept"
    get "bookings/:id/reject" => "bookings#reject"
    get "bookings/:id/cancel_by_host" => "bookings#cancel_by_host"
  end


  # Dashboard
  # Shows next bookings (nomad)
  # Shows pending booking requests (host)
  # Shows big picture of community interaction later
  # get "dashboard"


  # New booking 
  # /bookings/new

  # Dashboard
  # 
  # See current bookings as a host
  # /host/dashboard
  # See current bookings as a nomad
  # /nomad/dashboard

  # Show
  # 
  # See a booking as a nomad
  # /nomad/booking/id
  # See and manage a booking as a host 
  # /host/booking/id



  # Example of regular route:
  #   get "products/:id" => "catalog#view"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get "products/:id/purchase" => "catalog#purchase", as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get "short"
  #       post "toggle"
  #     end
  #
  #     collection do
  #       get "sold"
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get "recent", on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post "toggle"
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :house
	belongs_to :apartment

  validates_presence_of       :title
  
  validates :sqm,                        numericality: { only_integer: true, greater_than: 0 }
  validates :monthly_price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  validates_inclusion_of :desk, in: [true, false]
  validates_inclusion_of :kitchen_access, in: [true, false]
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  public

    def show
      @stay = Stay.find params[:stay_id]
      @room = Room.find params[:id]
    end

  	def new
  		@stay = Stay.find params[:stay_id]
  		@room = Room.new 
  	end

  	def create
      @stay = Stay.find(params[:stay_id])
  		@room = Room.new(room_params)
      @room.stay_id = @stay.id

      # Rooms are linked to an apartment or a house, not to a stay
      # if @stay.house
        # @room.house_id = @stay.house.id
      # elsif @stay.apartment
        # @room.apartment_id = @stay.apartment.id
      # end      

  		@room.save

    	if @room.persisted?
    		redirect_to stay_room_path(stay_id: @stay.id, id: @room.id)
    	else
    		render "new"
    	end
  	end	

    def edit
      @room = Room.find params[:id]
      @stay = Stay.find params[:stay_id]
    end

    def update
      @room = Room.find(params[:id])
      @stay = Stay.find params[:stay_id]

      if @room.update(room_params)
        redirect_to stay_room_path(stay_id: @stay.id, id: @room.id)
      else
        render "edit"
      end         
    end

    def destroy
      @room = Room.find(params[:id])
      @stay = Stay.find(params[:stay_id])
      @room.destroy
      redirect_to stay_path(id: @stay.id)
    end

  private

    def room_params
      params.require(:room).permit(:title, :sqm, :desk, :kitchen_access, :monthly_price)
    end  

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.haml
%h3 Add a new room in #{@stay.title}

= simple_form_for(@room, :url => stay_room_path(stay_id: @stay.id, id: @room.id), :method => "put") do |f|
  = f.input :title
  = f.hint "Make it appealing ! 'Spacious room on the sunny east side'"
  = f.input :sqm, label: "How big is this room ?"
  = f.hint "Only approximately, in square meters"
  = f.input :desk, label: "Does it have a desk ?"
  = f.hint "Remember, a nomad will spend most of his time working !"
  = f.input :kitchen_access, label: "Are nomads free to use to the kitchen ?"

  = f.button :submit, "Add"

app/views/rooms/new.haml
%h3 Add a new room in #{@stay.title}

= simple_form_for(@room, :url => stay_rooms_path(@stay.id)) do |f|
  = f.input :title
  = f.hint "Make it appealing ! 'Spacious room on the sunny east side'"
  = f.input :sqm, label: "How big is this room ?"
  = f.hint "Only approximately, in square meters"
  = f.input :desk, label: "Does it have a desk ?"
  = f.hint "Remember, a nomad will spend most of his time working !"
  = f.input :kitchen_access, label: "Are nomads free to use to the kitchen ?"

  = f.input :monthly_price, wrapper: :vertical_input_group, hint: "Remember, the minimum stay length will be 1 month" do
    %span.input-group-addon US $
    = f.input_field :monthly_price, class: "form-control"  

  = f.button :submit, "Add"

app/views/rooms/show.haml
%h3 This is the room #{@room.title}

%p= link_to "Edit this room", edit_stay_room_path(stay_id: @stay.id, id: @room.id)
%p= link_to "Remove this room", stay_room_path(stay_id: @stay.id, id: @room.id), :method => "delete"