config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: "registrations" }, class_name: "FormUser"
  get "users/:id" => "users#profile"

  # Bookings
  resources :bookings
  get "bookings/:id/cancel_by_nomad" => "bookings#cancel_by_nomad"    

  get "bookings/:id/payment" => "bookings#payment"
  get "bookings/:id/pay" => "bookings#pay"

  get "bookings/:id/payment_cancelled" => "bookings#payment_cancelled"
  get "bookings/:id/payment_received" =>  "bookings#payment_received"

  get  "stay/:stay_id/room/:room_id/book" => "bookings#new"
  post "stay/:stay_id/room/:room_id/book" => "bookings#create"

  # Stays, rooms, bookings
  resources :stays do
    resources :rooms
  end  

  # Stay photos
  resources :stay_photos 
  get "stay_photos/:id/set_as_cover" => "stay_photos#set_as_cover"

  # Admin
  namespace :admin do
    resources :stays
    resources :bookings

    get "bookings/:id/accept" => "bookings#accept"
    get "bookings/:id/reject" => "bookings#reject"
    get "bookings/:id/cancel_by_host" => "bookings#cancel_by_host"
  end


  # Dashboard
  # Shows next bookings (nomad)
  # Shows pending booking requests (host)
  # Shows big picture of community interaction later
  # get "dashboard"


  # New booking 
  # /bookings/new

  # Dashboard
  # 
  # See current bookings as a host
  # /host/dashboard
  # See current bookings as a nomad
  # /nomad/dashboard

  # Show
  # 
  # See a booking as a nomad
  # /nomad/booking/id
  # See and manage a booking as a host 
  # /host/booking/id



  # Example of regular route:
  #   get "products/:id" => "catalog#view"

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get "products/:id/purchase" => "catalog#purchase", as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get "short"
  #       post "toggle"
  #     end
  #
  #     collection do
  #       get "sold"
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get "recent", on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post "toggle"
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/header/_header.haml
.header
  .row
    .col-md-1
      .logo
        = link_to root_path do
          = image_tag "Logo_06.png"    
    .col-md-11
      .title
        = yield :title

app/views/header/_subheader.haml
.subheader

  = yield :subheader

  / / Search

  / = link_to search_path do
  /   / %button.btn.btn-primary{:type => "button"}
  /   %span.glyphicon.glyphicon-search{"aria-hidden" => "true"}

  / / Bookings

  / - if current_user && current_user.bookings.any?
  /   = link_to bookings_path do 
  /     / %button.btn.btn-primary{:type => "button"}   
  /     %span.glyphicon.glyphicon-briefcase{"aria-hidden" => "true"}

  / / Host dashboard

  / - if current_user && current_user.stays.any?
  /   = link_to dashboard_path do 
  /     / %button.btn.btn-primary{:type => "button"}   
  /     %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}

  / / Favorite

  / / %button.btn.btn-primary{:type => "button"}    
  / %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}

  / / User profile

  / - if current_user
  /  = link_to profile_path do 
  /    %button.btn.btn-primary{:type => "button"}   
  /      %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}    